In [3]:
import numpy as np

m = np.arange(10, dtype=np.float64)
f = np.arange(10) * 2
a = np.arange(10) ** 2.

m, f, a

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.]))

In [ ]:

ddof = 1
w = f * a

v1 = np.sum(w)
v2 = np.sum(w * a)
m -= np.sum(m * w, axis=None, keepdims=True) / v1
cov = np.dot(m * w, m.T) * v1 / (v1**2 - ddof * v2)


In [4]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T
x

array([[0, 1, 2],
       [2, 1, 0]])

In [5]:
np.cov(x)


array([[ 1., -1.],
       [-1.,  1.]])

In [7]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]

X = np.stack((x, y), axis=0)

np.cov(X), X

(array([[11.71      , -4.286     ],
        [-4.286     ,  2.14413333]]),
 array([[-2.1 , -1.  ,  4.3 ],
        [ 3.  ,  1.1 ,  0.12]]))

In [ ]:
asset_returns = """
Date,Asset1,Asset2,Asset3,Asset4
2023-01-01,0.02,0.03,0.015,0.01
2023-01-02,0.015,0.025,0.012,0.008
2023-01-03,-0.01,-0.02,-0.005,-0.003
2023-01-04,0.03,0.035,0.018,0.015
2023-01-05,0.012,0.02,0.01,0.007
"""

import pandas as pd